### ISSUE TITLE
Service Will Not Start

### ISSUE THREAD

**Issue by l33mm** [bmanojlovic/dbforbix#1]
No matter what I have tried the service refuses to start.
Running CentOS 7.
Below is the error I always receive.

dbforbix.service - DBforBIX Monitoring Agent
   Loaded: loaded (/etc/systemd/system/dbforbix.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2016-11-03 20:21:14 CDT; 2min 16s ago
  Process: 2996 ExecStart=/opt/dbforbix/dbforbix.sh start (code=exited, status=203/EXEC)

Nov 03 20:21:14 zabbix01 systemd[1]: Starting DBforBIX Monitoring Agent...
Nov 03 20:21:14 zabbix01 systemd[1]: dbforbix.service: control process exited, code=exited status=203
Nov 03 20:21:14 zabbix01 systemd[1]: Failed to start DBforBIX Monitoring Agent.
Nov 03 20:21:14 zabbix01 systemd[1]: Unit dbforbix.service entered failed state.
Nov 03 20:21:14 zabbix01 systemd[1]: dbforbix.service failed.

**Comment by bmanojlovic** [comment]
Sorry for slow response, look at binary packages of this software at sf.net/projects/dbforbix by original author
