### ISSUE TITLE
dbforbix-2.2-beta-ilnux64 oracle

### ISSUE THREAD

**Issue by askifyouneed** [bmanojlovic/dbforbix#2]
I can't see in the version 2.2 in the file META-INF/MANIFEST.MF the Class-Path to ojdbc driver like it was in the previous versions.
And there is no configuration for Oracle in the config.properties.sample also.

**Comment by bmanojlovic** [comment]
reason why there ius no any info regarding 2.2 is like i have already stated on main page of this repository I'm not developer of this software. Anyway i will import sources as is from -src archive found on sourceforge just for convenience.

**Comment by bmanojlovic** [comment]
There is change in logic regarding items generated please look at items/ folder for clues

**Comment by askifyouneed** [comment]
I'm sorry? My obvious mistake:)

**Comment by bmanojlovic** [comment]
if it was not clear (sorry not native english speaker :) ) , items that will be pushed to zabbix are now located in <unpacked_archive>/items folder inside of specific .xml file such as example from bellow from oracle.xml
```
 <query time="120" item="locked_users" nodata="0">SELECT COUNT(*) AS c FROM dba_users WHERE account_status IN('EXPIRED(GRACE)','LOCKED(TIMED)')</query>
```
